import type { ReceiptDetail, Stats, Observation } from '@bowl/shared';
// Synthetic display data only. Never uploaded, stored in the canonical DB, or mixed with real receipts.
export const demoStats: Stats = {
  spend_cents: 82456,
  visits: 18,
  average_basket_cents: 4581,
  line_items: 237,
  produce_pounds: 86.4,
  review_included: 1,
  excluded_currency: 0,
  undated_receipts: 0,
  months: [
    { period: '2026-04-01', spend_cents: 11834, visits: 3 },
    { period: '2026-05-01', spend_cents: 16250, visits: 4 },
    { period: '2026-06-01', spend_cents: 13988, visits: 3 },
    { period: '2026-07-01', spend_cents: 18020, visits: 4 },
    { period: '2026-08-01', spend_cents: 14144, visits: 3 },
    { period: '2026-09-01', spend_cents: 8220, visits: 1 },
  ],
  products: [
    {
      key: 'apples',
      name: 'Honeycrisp apples',
      merchant: 'Berkeley Bowl',
      code: '3283',
      unit: 'lb',
      visits: 12,
      spend_cents: 6820,
      pounds: 19.4,
      aliases: ['ORG HNYCRISP', 'HONEYCRISP APP'],
    },
    {
      key: 'avocado',
      name: 'Hass avocados',
      merchant: 'Berkeley Bowl',
      code: '4046',
      unit: 'each',
      visits: 10,
      spend_cents: 2450,
      pounds: 0,
      aliases: ['HASS AVO'],
    },
    {
      key: 'tomato',
      name: 'Heirloom tomatoes',
      merchant: 'Berkeley Bowl',
      code: '3423',
      unit: 'lb',
      visits: 8,
      spend_cents: 4320,
      pounds: 12.8,
      aliases: ['HEIRLOOM TOM'],
    },
  ],
};
export const demoReceipt: ReceiptDetail = {
  id: 'demo',
  merchant: 'Berkeley Bowl',
  store_location: '2020 Oregon Street',
  purchased_at: '2026-09-12',
  currency: 'USD',
  subtotal_cents: 4080,
  tax_cents: 0,
  discounts_cents: 0,
  fees_cents: 0,
  total_cents: 4080,
  status: 'processed',
  item_count: 3,
  created_at: '2026-09-12T20:00:00Z',
  updated_at: '2026-09-12T20:00:00Z',
  revision: 1,
  reconciliation_delta_cents: 0,
  reconciliation_reason: null,
  last_error: null,
  raw_extraction: {
    note: 'Synthetic demo — not a transcription of a real receipt.',
  },
  attempts: [],
  line_items: [
    {
      merchant_item_code: '3283',
      raw_description: 'ORG HNYCRISP',
      normalized_description: 'Honeycrisp apples',
      category: 'produce',
      quantity: '3.000',
      unit: 'lb',
      unit_price_cents: 399,
      extended_price_cents: 1197,
      line_discount_cents: 0,
      raw_line: '3283 ORG HNYCRISP 3.00 lb @ 3.99',
    },
    {
      merchant_item_code: '4046',
      raw_description: 'HASS AVO',
      normalized_description: 'Hass avocados',
      category: 'produce',
      quantity: '3',
      unit: 'each',
      unit_price_cents: 199,
      extended_price_cents: 597,
      line_discount_cents: 0,
      raw_line: null,
    },
    {
      merchant_item_code: null,
      raw_description: 'PANTRY ITEMS',
      normalized_description: 'Pantry items',
      category: 'other',
      quantity: '1',
      unit: 'each',
      unit_price_cents: 2286,
      extended_price_cents: 2286,
      line_discount_cents: 0,
      raw_line: null,
    },
  ],
};
export const demoHistory: Observation[] = [399, 349, 449, 399].map((p, i) => ({
  receipt_id: 'demo',
  purchased_at: `2026-0${6 + i}-12`,
  unit_price_cents: p,
  extended_price_cents: p * 3,
  quantity: '3',
  unit: 'lb',
  raw_description: 'ORG HNYCRISP',
}));
